version: '3.3'

services:
  redis:
    image: redis
    ports:
      - :6379
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A web_events_list worker
    volumes:
      - .:/usr/src/web_events_list
    links:
      - redis
    depends_on:
      - redis
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/web_events_list
    ports:
      - 8000:8000
    depends_on:
      - celery
    links:
      - redis
      - celery

